# permissions for end users to edit gpus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-editor-role
rules:
- apiGroups:
  - scheduling.volcano.sh
  resources:
  - gpus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.volcano.sh
  resources:
  - gpus/status
  verbs:
  - get
