# permissions for end users to view gpus.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-viewer-role
rules:
- apiGroups:
  - scheduling.volcano.sh
  resources:
  - gpus
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.volcano.sh
  resources:
  - gpus/status
  verbs:
  - get
